### PR TITLE
support mongodb

### PR DESCRIPTION
**Pull request by caosiyang**
- support mongodb
- update README

### CODE REVIEW

**Comment by siddontang** [comment]
Thanks @caosiyang 

Can you update go.mod?

**Comment by caosiyang** [comment]
No problem. Fix it later.

**Comment by caosiyang** [comment]
Can I know the version of Go that you use?

**Comment by siddontang** [comment]
I use go 1.12, but I know that go 1.14 has a problem when compiling go-ycsb now.
I suggest you can use go 1.14 and remove go.sum, then build go-ycsb.

**Comment by caosiyang** [comment]
Yeah, go 1.11.4 reports "checksum dismatch" error and reinstall 1.11.3 is pass.
I will rebuild it with go 1.11.4  as you suggest.

Another question, I cannot visit package "honnef.co/go/tools",  error as follows:
```
$ go build -o bin/go-ycsb cmd/go-ycsb/*
go: honnef.co/go/tools@v0.0.0-20180920025451-e3ad64cb4ed3: unrecognized import path "honnef.co/go/tools" (https fetch: Get https://honnef.co/go/tools?go-get=1: net/http: TLS handshake timeout)
go: honnef.co/go/tools@v0.0.0-20180728063816-88497007e858: unrecognized import path "honnef.co/go/tools" (https fetch: Get https://honnef.co/go/tools?go-get=1: net/http: TLS handshake timeout)
go: error loading module requirements
```

Can I add the following line into go.mod?
`replace honnef.co/go/tools => github.com/dominikh/go-tools v0.0.0-20180920025451-e3ad64cb4ed3`

**Comment by siddontang** [comment]
@caosiyang 

seem you need to cross the wall :sob:

**Comment by siddontang** [comment]
can you help us change `https://github.com/pingcap/go-ycsb/blob/master/Dockerfile#L1` here to use go 1.11.4?

**Comment by siddontang** [comment]
oh, sadly, I use your branch but can't build in my computer

```
go: verifying github.com/coreos/etcd@v3.3.10+incompatible: checksum mismatch
	downloaded: h1:KjVWqrZ5U0wa3CxY2AxlH6/UcB+PK2td1DcsYhA+HRs=
	go.sum:     h1:jFneRYjIvLMLhDLCzuTuU4rSJUjRplcJQ7pD7MnhC04=
```

**Comment by caosiyang** [comment]
My Linux cannot cross the wall, so I build it under Mingw32 in Windows7(32bit).
I'm not sure if problem is here.

**Comment by siddontang** [comment]
@caosiyang 

Do you use Linux or MacOS?

**Comment by siddontang** [comment]
My Linux can pass the compile but my Mac OSX can't......

**Comment by siddontang** [comment]
I will check this problem later, thank you.

**Pull request merged**
